################################################################################################
# Submission by slk522
# Attack Scenario 8 - Check if Existing File can be opened with create parameter as False
# 9 Security Layers are Secure
# 1 logged ERROR ATTACK - 8 | Not Allowing to open existing file!
# 14 failed due to Fatal Error
# 7 failed due to Uncaught Repy Exception
################################################################################################

# Clean up of existing file
if "testfile.txt.a" in listfiles():
  removefile("testfile.txt.a")
if "testfile.txt.b" in listfiles():
  removefile("testfile.txt.b")

# Open File Function Call
myfile=ABopenfile("testfile.txt",True)

#Close the file
myfile.close()

# File should exist, since removed function not called
# Open File Function Call, again
try:
  myfile=ABopenfile("testfile.txt",False)
except:
  log("ERROR ATTACK - 8 | Not Allowing to open existing file! \n")

#Close the file
myfile.close()
